// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: "postgresql://neondb_owner:npg_QtpEjVg9R4vO@ep-divine-credit-aoeac9ik.c-2.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require"
  },
});
